#!/usr/bin/env python3
"""
Safely move or remove duplicate files based on `tools/duplicate_contents.txt`.
By default this moves duplicates (keeps one copy) into a quarantine folder.

Usage examples (run from repository root):
  python tools/remove_duplicates_safe.py --mode quarantine --dry-run
  python tools/remove_duplicates_safe.py --mode quarantine
  python tools/remove_duplicates_safe.py --mode delete --confirm   # irreversible

The script requires the `duplicate_contents.txt` previously generated by the scanner.
"""
from __future__ import annotations
import argparse
import os
import shutil
import sys
import time
from pathlib import Path
from typing import Iterator, List, Tuple


def parse_duplicate_contents_file(path: Path) -> Iterator[Tuple[str, List[str]]]:
    cur_hash = None
    cur_paths: List[str] = []
    with path.open("r", encoding="utf-8", errors="ignore") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if line.startswith("hash:"):
                if cur_hash and len(cur_paths) > 1:
                    yield cur_hash, cur_paths
                cur_hash = line.split("hash:", 1)[1].strip()
                cur_paths = []
            elif line.startswith("    ") or line.startswith("\t"):
                p = line.strip()
                if p:
                    cur_paths.append(p)
            elif not line.strip():
                if cur_hash and len(cur_paths) > 1:
                    yield cur_hash, cur_paths
                cur_hash = None
                cur_paths = []
    if cur_hash and len(cur_paths) > 1:
        yield cur_hash, cur_paths


def unique_dest(dest_dir: Path, name: str) -> Path:
    candidate = dest_dir / name
    if not candidate.exists():
        return candidate
    stem = Path(name).stem
    suffix = Path(name).suffix
    i = 1
    while True:
        candidate = dest_dir / f"{stem}_{i}{suffix}"
        if not candidate.exists():
            return candidate
        i += 1


def choose_keep_path(paths: List[Path], policy: str) -> Path:
    if policy == "first":
        return sorted(paths, key=lambda p: str(p).lower())[0]
    if policy == "shortest":
        return min(paths, key=lambda p: len(str(p)))
    if policy == "oldest":
        return min(paths, key=lambda p: p.stat().st_mtime)
    if policy == "newest":
        return max(paths, key=lambda p: p.stat().st_mtime)
    return sorted(paths, key=lambda p: str(p).lower())[0]


def human_size(n: int) -> str:
    for unit in ["B", "KB", "MB", "GB"]:
        if n < 1024.0:
            return f"{n:.1f}{unit}"
        n /= 1024.0
    return f"{n:.1f}TB"


def main() -> None:
    parser = argparse.ArgumentParser(description="Safely move or delete duplicate files")
    parser.add_argument("--duplicate-file", "-f", default=None,
                        help="Path to duplicate_contents.txt (default: tools/duplicate_contents.txt)")
    parser.add_argument("--mode", choices=["quarantine", "delete"], default="quarantine",
                        help="Action to take on duplicates: quarantine (move) or delete (permanent)")
    parser.add_argument("--quarantine-dir", default=None, help="Custom quarantine directory")
    parser.add_argument("--dry-run", action="store_true", help="Show actions without making changes")
    parser.add_argument("--confirm", action="store_true", help="Required to perform permanent deletes")
    parser.add_argument("--keep", choices=["first", "shortest", "oldest", "newest"], default="first",
                        help="Which file to keep among duplicates")
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent
    default_dup_file = script_dir / "duplicate_contents.txt"
    dup_file = Path(args.duplicate_file).resolve() if args.duplicate_file else default_dup_file

    if not dup_file.exists():
        print(f"Duplicate contents file not found: {dup_file}")
        print("Run tools/find_duplicates.py first to generate reports.")
        sys.exit(1)

    timestamp = time.strftime("%Y%m%d_%H%M%S")
    default_quarantine = repo_root / "tools" / f"duplicates_quarantine_{timestamp}"
    quarantine_dir = Path(args.quarantine_dir).resolve() if args.quarantine_dir else default_quarantine

    if args.mode == "delete" and not args.confirm:
        print("Permanent delete requires --confirm to proceed. Aborting.")
        sys.exit(1)

    print(f"Mode: {args.mode}  dry-run: {args.dry_run}  keep: {args.keep}")
    print(f"Reading duplicates from: {dup_file}")
    print(f"Quarantine dir: {quarantine_dir}")

    if not args.dry_run:
        quarantine_dir.mkdir(parents=True, exist_ok=True)

    mapping_log = quarantine_dir / "quarantine_map.txt"
    moved_count = 0
    deleted_count = 0
    moved_bytes = 0
    deleted_bytes = 0
    groups_processed = 0
    errors = []

    for h, paths in parse_duplicate_contents_file(dup_file):
        groups_processed += 1
        # resolve and filter
        resolved = []
        for p in paths:
            try:
                rp = Path(p).resolve()
            except Exception:
                continue
            # skip files already in our quarantine dir
            if quarantine_dir in rp.parents:
                continue
            if not rp.exists():
                continue
            # skip the duplicate report files themselves
            if rp.samefile(dup_file) if dup_file.exists() else False:
                continue
            # skip this script file
            try:
                if rp.samefile(Path(__file__).resolve()):
                    continue
            except Exception:
                pass
            resolved.append(rp)

        if len(resolved) <= 1:
            continue

        try:
            keep_path = choose_keep_path(resolved, args.keep)
        except Exception:
            keep_path = resolved[0]

        for p in resolved:
            if p == keep_path:
                continue
            try:
                size = p.stat().st_size
            except Exception:
                size = 0
            if args.mode == "quarantine":
                dest_dir = quarantine_dir / h
                dest_name = p.name
                dest_path = unique_dest(dest_dir, dest_name)
                if args.dry_run:
                    print(f"Would move: {p} -> {dest_path}")
                else:
                    dest_dir.mkdir(parents=True, exist_ok=True)
                    try:
                        shutil.move(str(p), str(dest_path))
                        moved_count += 1
                        moved_bytes += size
                        with mapping_log.open("a", encoding="utf-8") as mf:
                            mf.write(f"MOVE {p} -> {dest_path}\n")
                    except Exception as e:
                        errors.append((p, e))
            else:  # delete
                if args.dry_run:
                    print(f"Would delete: {p}")
                else:
                    try:
                        p.unlink()
                        deleted_count += 1
                        deleted_bytes += size
                        with mapping_log.open("a", encoding="utf-8") as mf:
                            mf.write(f"DELETE {p}\n")
                    except Exception as e:
                        errors.append((p, e))

    print("\nDone.")
    print(f"Groups processed: {groups_processed}")
    if args.mode == "quarantine":
        print(f"Files moved: {moved_count}  ({human_size(moved_bytes)})")
        print(f"Mapping log: {mapping_log}")
    else:
        print(f"Files deleted: {deleted_count}  ({human_size(deleted_bytes)})")
    if errors:
        print(f"Errors: {len(errors)} (first 5 shown)")
        for e in errors[:5]:
            print(e[0], "->", e[1])
    print("Review the quarantine folder before permanently deleting anything.")


if __name__ == "__main__":
    main()
